## Numpy array and basics
Learn about numpy with Chai aur Code

In [2]:
import numpy as np
import time

### Creating array from list

In [2]:
arr_1d = np.array([1, 2, 3])
print("1D Array:", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr_2d)

1D Array: [1 2 3]
2D Array:
 [[1 2 3]
 [4 5 6]]


### List vs Numpy array

In [2]:
py_list = [1, 2, 3]
print("Python list Multiplication: ", py_list*2)

np_array = np.array([2, 4, 6])
print("Python array Multiplication: ", np_array*2)

Python list Multiplication:  [1, 2, 3, 1, 2, 3]
Python array Multiplication:  [ 4  8 12]


### Comparison

In [3]:
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)


 List operation time:  0.1277153491973877

 Numpy operation time:  0.009083271026611328


### Creating array ftom scratch

In [3]:
zeros = np.zeros((3, 4))
print("Zero matrix:\n", zeros)

ones = np.ones((3, 4))
print("\nUnit Matrix: \n", ones)

full = np.full((3, 4), 5)
print("\n3 x 4 matrix with all values 5:\n", full)

random = np.random.rand(2, 3)
print("\nRandom Array:\n", random) 

sequence = np.arange(0, 11, 2)
print("\nSequence Array:", sequence)

Zero matrix:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Unit Matrix: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

3 x 4 matrix with all values 5:
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]

Random Array:
 [[0.13967922 0.87295465 0.63898344]
 [0.94676333 0.11852552 0.22891186]]

Sequence Array: [ 0  2  4  6  8 10]


### Vector, Matrix & Tensor

In [5]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("\nMatrix:\n", matrix)

tensor = np.array([[[1, 2], [3, 4]], [[9, 8], [7, 6]]])
print("\nTensor:\n", tensor)

Vector:  [1 2 3]

Matrix:
 [[1 2 3]
 [4 5 6]]

Tensor:
 [[[1 2]
  [3 4]]

 [[9 8]
  [7 6]]]


### Array Properties

In [6]:
arr = np.array([[1, 2, 3],
               [4, 5, 6]])
print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("Datatype: ", arr.dtype)

Shape:  (2, 3)
Dimension:  2
Size:  6
Datatype:  int64


### Array Reshaping

In [7]:
arr = np.arange(12)
print("\nOriginal array: ", arr)

reshaped = arr.reshape((3, 4))
print("\nReshaped array:\n", reshaped)

flattened = reshaped.flatten()
print("\nFlattened array: ", flattened)

# Returns view instead of copy
raveled = reshaped.ravel()
print("\nRaveled array: ", raveled)

transposed = reshaped.T
print("\nTransposed array:\n", transposed)


Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transposed array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## End of Phase-1