# Numpy Array Operations

In [ ]:
import numpy as np

In [ ]:
arr = np.array([i for i in range(0, 10)])
print("Array: ", arr)
print("Basic Slicing: ", arr[2:7])
print("With Step: ", arr[1: 10: 2])
print("Negative indexing: ", arr[-1])

In [ ]:
arr_2d = np.array([[1, 2, 3],
               [4, 5, 6],
                [7, 8, 9]])
print("Array:\n", arr_2d)
print("Specific element (0th row, 2nd column): ", arr_2d[0, 2])
print("Specific row (1st row): ", arr_2d[1])
print("Specific column (0th column): ", arr_2d[:, 0])

## Sorting

In [ ]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted Array: ", np.sort(unsorted))

uns_2d_arr = np.array([[2, 1],
                       [4, 3],
                       [1, 2]])
print("\nSorted Array by Column:\n", np.sort(uns_2d_arr, axis = 0))
print("\nSorted Array by Row:\n", np.sort(uns_2d_arr, axis = 1))

## Filter

In [ ]:
numbers = np.array([i for i in range(1, 11)]) # [1, 2, 3, 4, 5, 6, 7, 8, 8, 10]
even_numbers = numbers[numbers % 2 == 0]
print("Even Numbers:", even_numbers)

### Filter with mask

In [ ]:
mask = numbers > 5
print("Numebrs greater than 5: ", numbers[mask])

## Fancy Indexing vs np.where()

In [ ]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("np Where: ", numbers[where_result])

In [ ]:
# np.where(condition, "true", "false")
condition_array = np.where(numbers > 5, numbers*2, numbers)
print(condition_array)

## Adding and Removing Data

In [30]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


### Array Compatibility

In [34]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print("Compatibility Shapes: ", a.shape == b.shape == c.shape)

Compatibility Shapes:  True


### Adding Rows/Columns

In [43]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])
with_new_row = np.vstack((original, new_row))

print("Original:\n", original)
print("\nWith new row:\n", with_new_row)

new_column = np.array([[7], [8]])
with_new_col = np.hstack((original, new_column))

print("\nWith new column:\n", with_new_col)

Original:
 [[1 2]
 [3 4]]

With new row:
 [[1 2]
 [3 4]
 [5 6]]

With new column:
 [[1 2 7]
 [3 4 8]]


### Removing Rows/Columns

In [51]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
deleted = np.delete(arr, 1)
print("Array after deletion: ", deleted)

Array after deletion:  [ 1  3  4  5  6  7  8  9 10]


## End of Phase 2